### ISSUE TITLE
Error: Cannot find module 'http-errors'

### ISSUE THREAD

**Issue by kingfisheranalytics** [soliantconsulting/FileMakerID_token#4]
OSX 10.15.7.  Initial install on Visual Studio Code v.1.50.1 - fails following install instruction.  

Error trace:
Error: Cannot find module 'http-errors'
Require stack:
- /Users/######/Desktop/FileMakerID_token-master/app.js
- /Users/######/Desktop/FileMakerID_token-master/bin/www
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/guy2019/Desktop/FileMakerID_token-master/app.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/######/Desktop/FileMakerID_token-master/app.js',
    '/Users/######/Desktop/FileMakerID_token-master/bin/www'
  ]
}

**Comment by wimdecorte** [comment]
Did you do "npm install" from the command line in the folder where you downloaded the node code?

**Comment by huguesl** [comment]
I'm on mac and getting the same error as above. I did run npm install, it installed packages but does not resolve the issue.

**Comment by wimdecorte** [comment]
from inside the project folder, run the install command listed to the right on https://www.npmjs.com/package/http-errors

**Comment by huguesl** [comment]
Thank you, I installed that package, ran npm install again... everything looks fine but not able to hit the users route for some reason. I just realized it's not the same error message! Read it too quickly. Below is the actual error message, in case you're interested in it. I need to host a solution within Unity3d which doesn't support node.js so I won't be able to reuse this solution anyways. I found another resource that shows how to do it within unity. I will try that. I just wanted to try this solution to have a quick way to test different endpoints. Thanks again.

<body>
	<h1>Not Found</h1>
	<h2>404</h2>
	<pre>NotFoundError: Not Found
    at /Users/##/Desktop/Downloads/FileMakerID_token-master/app.js:27:8
    at Layer.handle [as handle_request] (/Users/##/Desktop/Downloads/FileMakerID_token-master/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/##/Desktop/Downloads/FileMakerID_token-master/node_modules/express/lib/router/index.js:317:13)
    at /Users/##/Desktop/Downloads/FileMakerID_token-master/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/##/Desktop/Downloads/FileMakerID_token-master/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/##/Desktop/Downloads/FileMakerID_token-master/node_modules/express/lib/router/index.js:275:10)
    at /Users/##/Desktop/Downloads/FileMakerID_token-master/node_modules/express/lib/router/index.js:635:15
    at next (/Users/##/Desktop/Downloads/FileMakerID_token-master/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/Users/##/Desktop/Downloads/FileMakerID_token-master/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/##/Desktop/Downloads/FileMakerID_token-master/node_modules/express/lib/router/index.js:47:12)</pre>
</body>
